apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: nexus3
    namespace: ak-nexus
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: sonatype/nexus3:latest
      generation: 1
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: docker-registry.default.svc:5000/ak-nexus/nexus3
    tags:
    - items:
      -
      tag: latest
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""